/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerOption { 'englishText' : string, 'hindiText' : string }
export interface PersonalityType {
  'englishFamousExamples' : Array<string>,
  'englishStrengths' : Array<string>,
  'hindiDescription' : string,
  'code' : string,
  'englishName' : string,
  'hindiName' : string,
  'englishDescription' : string,
  'category' : string,
  'hindiFamousExamples' : Array<string>,
  'englishWeaknesses' : Array<string>,
  'hindiWeaknesses' : Array<string>,
  'hindiStrengths' : Array<string>,
}
export interface QuizQuestion {
  'answerOptions' : Array<AnswerOption>,
  'dimension' : string,
  'englishText' : string,
  'hindiText' : string,
}
export interface _SERVICE {
  'calculatePersonalityType' : ActorMethod<[Array<bigint>], string>,
  'getAllPersonalityTypes' : ActorMethod<[], Array<PersonalityType>>,
  'getAllQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getPersonalityTypeByCode' : ActorMethod<[string], PersonalityType>,
  'getQuizQuestionById' : ActorMethod<[string], QuizQuestion>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];