/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersonalityType = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'famousExamples' : IDL.Vec(IDL.Text),
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'likes' : IDL.Vec(IDL.Text),
  'dislikes' : IDL.Vec(IDL.Text),
});
export const AnswerOption = IDL.Record({
  'text' : IDL.Text,
  'dimension' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'answerOptions' : IDL.Vec(AnswerOption),
  'dimension' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculatePersonalityType' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Text], []),
  'getAllPersonalityTypes' : IDL.Func(
      [],
      [IDL.Vec(PersonalityType)],
      ['query'],
    ),
  'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getPersonalityTypeByCode' : IDL.Func(
      [IDL.Text],
      [PersonalityType],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersonalityType = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'famousExamples' : IDL.Vec(IDL.Text),
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'likes' : IDL.Vec(IDL.Text),
    'dislikes' : IDL.Vec(IDL.Text),
  });
  const AnswerOption = IDL.Record({
    'text' : IDL.Text,
    'dimension' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'answerOptions' : IDL.Vec(AnswerOption),
    'dimension' : IDL.Text,
  });
  
  return IDL.Service({
    'calculatePersonalityType' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Text], []),
    'getAllPersonalityTypes' : IDL.Func(
        [],
        [IDL.Vec(PersonalityType)],
        ['query'],
      ),
    'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getPersonalityTypeByCode' : IDL.Func(
        [IDL.Text],
        [PersonalityType],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };