/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersonalityType = IDL.Record({
  'englishFamousExamples' : IDL.Vec(IDL.Text),
  'englishStrengths' : IDL.Vec(IDL.Text),
  'hindiDescription' : IDL.Text,
  'code' : IDL.Text,
  'englishName' : IDL.Text,
  'hindiName' : IDL.Text,
  'englishDescription' : IDL.Text,
  'category' : IDL.Text,
  'hindiFamousExamples' : IDL.Vec(IDL.Text),
  'englishWeaknesses' : IDL.Vec(IDL.Text),
  'hindiWeaknesses' : IDL.Vec(IDL.Text),
  'hindiStrengths' : IDL.Vec(IDL.Text),
});
export const AnswerOption = IDL.Record({
  'englishText' : IDL.Text,
  'hindiText' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'answerOptions' : IDL.Vec(AnswerOption),
  'dimension' : IDL.Text,
  'englishText' : IDL.Text,
  'hindiText' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculatePersonalityType' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Text], []),
  'getAllPersonalityTypes' : IDL.Func(
      [],
      [IDL.Vec(PersonalityType)],
      ['query'],
    ),
  'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getPersonalityTypeByCode' : IDL.Func(
      [IDL.Text],
      [PersonalityType],
      ['query'],
    ),
  'getQuizQuestionById' : IDL.Func([IDL.Text], [QuizQuestion], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersonalityType = IDL.Record({
    'englishFamousExamples' : IDL.Vec(IDL.Text),
    'englishStrengths' : IDL.Vec(IDL.Text),
    'hindiDescription' : IDL.Text,
    'code' : IDL.Text,
    'englishName' : IDL.Text,
    'hindiName' : IDL.Text,
    'englishDescription' : IDL.Text,
    'category' : IDL.Text,
    'hindiFamousExamples' : IDL.Vec(IDL.Text),
    'englishWeaknesses' : IDL.Vec(IDL.Text),
    'hindiWeaknesses' : IDL.Vec(IDL.Text),
    'hindiStrengths' : IDL.Vec(IDL.Text),
  });
  const AnswerOption = IDL.Record({
    'englishText' : IDL.Text,
    'hindiText' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'answerOptions' : IDL.Vec(AnswerOption),
    'dimension' : IDL.Text,
    'englishText' : IDL.Text,
    'hindiText' : IDL.Text,
  });
  
  return IDL.Service({
    'calculatePersonalityType' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Text], []),
    'getAllPersonalityTypes' : IDL.Func(
        [],
        [IDL.Vec(PersonalityType)],
        ['query'],
      ),
    'getAllQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getPersonalityTypeByCode' : IDL.Func(
        [IDL.Text],
        [PersonalityType],
        ['query'],
      ),
    'getQuizQuestionById' : IDL.Func([IDL.Text], [QuizQuestion], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };